### ISSUE TITLE
I think "autostart.sh" should not be restricted with the root user check

### ISSUE THREAD

**Issue by oderwat** [janpfeifer/gonb#147]
I think the autostart.sh feature is cool, and we use it in multiple containers now. But I think it should work slightly different. Having GoNB checking it for being owned by root may pose a problem on Windows and is not nice on other systems either. You need to make it UID 0 on the host for that. I am not sure if that even is possible on Windows and I do not like to have a script like that owned by root on the host anyway. 

For added security one could mount that file as read only (`-v ./autostart.sh:/notebooks/autostart.sh:ro`). 

I actually also did not imagine that it is inside "notebooks". I thought it would just be in root and does not show up inside of JupyterLab.

**Comment by thevtm** [comment]
I agree.
In my set up I ended up overriding it using docker-compose.

```yaml
  gonb:
    image: "janpfeifer/gonb_jupyterlab:v0.10.6"
    entrypoint: ""
    command: ["tini", "-g", "--", "/notebooks/docker-compose/gonb/autostart.sh"]
    ports:
      - "58888:8888"
    volumes:
      - ./:/notebooks
    networks:
      - std-network
```

I don't know much about docker but I think we should use `CMD` instead of `ENTRYPOINT` [here](https://github.com/janpfeifer/gonb/blob/0745a3825ad8517a7a696403c013d1753d96ae51/Dockerfile#L105).
